const kernmap={
    "Roboto":{"kern":[
        {"letters":"ABCDGHKMNOPRSTUVWXYZ","kern":40},
        {"letters":"Q","kern":40},
        {"letters":"I","kern":17},
        {"letters":"1FJLEQ","kern":30},
        {"letters":"234567890_","kern":37}
    ],
    "font":"amelie","vsize":30},
    "Sora":{"kern":[
        {"letters":"ABCDGHKNOPRQSTUVXYZ","kern":133},
        {"letters":"MW","kern":140},
        {"letters":"I","kern":90},
        {"letters":"1EFJL","kern":125},
        {"letters":"234567890_","kern":133}
    ],
    "font":"anodine","vsize":30},
    "Hahmlet":{"kern":[
        {"letters":"ABCGHKMNOPRSTUVWXYZ","kern":46},
        {"letters":"DQ","kern":50},
        {"letters":"I","kern":18},
        {"letters":"1FJLEQ","kern":43},
        {"letters":"234567890_","kern":46}
    ],
    "font":"boomerang","vsize":30},
    "Poppins":{"kern":[
        {"letters":"ABCDEFGHMNOPUXYZ","kern":18},
        {"letters":"I","kern":10},
        {"letters":"1JKLRST","kern":15},
        {"letters":"QVW","kern":20},
        {"letters":"234567890_","kern":18}
    ],
    "font":"burstype","vsize":30},
    "Ubuntu":{"kern":[
        {"letters":"EGHKMNRTXYZ","kern":50},
        {"letters":"I","kern":30},
        {"letters":"1FJ","kern":40},
        {"letters":"BS","kern":41},
        {"letters":"DU","kern":44},
        {"letters":"PL","kern":43},
        {"letters":"ACQVWO","kern":55},
        {"letters":"234567890_","kern":50}
    ],
    "font":"cappuchino","vsize":30},
    "Open Sans":{"kern":[
        {"letters":"ABCGHKMNORSTUVWXYZ","kern":46},
        {"letters":"DQ","kern":50},
        {"letters":"I","kern":24},
        {"letters":"1FJLPEQ","kern":38},
        {"letters":"234567890_","kern":46}
    ],
    "font":"colloid","vsize":30},
    "Lato":{"kern":[
        {"letters":"ABDGHKNORUVXZ","kern":43},
        {"letters":"WMQ","kern":47},
        {"letters":"I","kern":24},
        {"letters":"L","kern":30},
        {"letters":"1CEFJPQSTY","kern":36},
        {"letters":"234567890_","kern":39}
    ],
    "font":"explodots","vsize":30},
    "Montserrat":{"kern":[
        {"letters":"ABCDEFGHKLMNOPQRSTUVXYZ","kern":35},
        {"letters":"I_","kern":15},
        {"letters":"1JK","kern":30},
        {"letters":"MW","kern":40},
        {"letters":"234567890","kern":36}
    ],
    "font":"hypernova","vsize":30},
    "Raleway":{"kern":[
        {"letters":"ABCDEGHKMNOPRQSTUVXYZ","kern":55},
        {"letters":"W","kern":65},
        {"letters":"I","kern":40},
        {"letters":"1FJL","kern":45},
        {"letters":"234567890_","kern":55}
    ],
    "font":"ink","vsize":30},
    "Epilogue":{"kern":[
        {"letters":"ABCDEGHKMNOPRQSTUVXYZ","kern":55},
        {"letters":"W","kern":65},
        {"letters":"I","kern":40},
        {"letters":"1FJL","kern":45},
        {"letters":"234567890_","kern":55}
    ],
    "font":"madita","vsize":30},
    "Press 2 Start":{"kern":[
        {"letters":"ABCDEGHJKNOPRSTUVXYZ","kern":98},
        {"letters":"QMW","kern":100},
        {"letters":"I","kern":70},
        {"letters":"1FL","kern":90},
        {"letters":"234567890_","kern":98}
    ],
    "font":"magnus","vsize":30,"colors":[]},
    "Roboto Condensed":{"kern":[
        {"letters":"ABCDEFGHKMNOPQRSTUVXYZ","kern":40},
        {"letters":"I","kern":20},
        {"letters":"_1FJL","kern":33},
        {"letters":"MW","kern":48},
        {"letters":"234567890","kern":40}
    ],
    "font":"multicolor","vsize":30},
    "Playfair Display":{"kern":[
        {"letters":"ABCDGHKNOPRQSTUVXYZ","kern":31},
        {"letters":"MW","kern":38},
        {"letters":"I","kern":14},
        {"letters":"FLEQ","kern":27},
        {"letters":"J","kern":24},
        {"letters":"1234567890_","kern":30}
    ],
    "font":"okomito","vsize":30},
    "Work Sans":{"kern":[
        {"letters":"ABCDEGHKNOPRSUVXYZ","kern":38},
        {"letters":"Q","kern":36},
        {"letters":"I","kern":15},
        {"letters":"1FJLT","kern":32},
        {"letters":"W","kern":48},
        {"letters":"M","kern":43},
        {"letters":"23456789_","kern":38}
    ],
    "font":"type36","vsize":30},
    "Source Sans Pro":{"kern":[
        {"letters":"ABCDEFGHKNOPQRTUVXYZ","kern":33},
        {"letters":"I","kern":20},
        {"letters":"17SFJL","kern":26},
        {"letters":"MW_","kern":40},
        {"letters":"23456890","kern":31}
    ],
    "font":"voyager","vsize":30}
}